-- 코드를 작성해주세요
SELECT 
    E.ID,
    IFNULL(C.CNT, 0) AS CHILD_COUNT 
FROM 
    ECOLI_DATA E 
LEFT JOIN 
(SELECT 
    E.PARENT_ID,
    COUNT(E.PARENT_ID) AS CNT 
FROM 
    ECOLI_DATA E 
GROUP BY 
    E.PARENT_ID) AS C ON E.ID = C.PARENT_ID 